
CREATE TABLE CLIENTE (
CodCli INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NomCli VARCHAR(25) NOT NULL,
ApeCli VARCHAR(25) NOT NULL,
Ape2Cli VARCHAR (25),
TelCli CHAR (9) NOT NULL CHECK (TelCli REGEXP '^[0-9]{9}$'),
EmailCli VARCHAR (254) NOT NULL CHECK (EmailCli REGEXP '^[^@]+@[^@]+\.[a-zA-Z]+$'),
DNICli CHAR(9) NOT NULL UNIQUE CHECK (DNICli REGEXP '^[0-9]{8}[A-Z]$' OR DNICli REGEXP '^[A-Z][0-9]{8}[A-Z]$')
);

CREATE TABLE ARTICULO(
CodArt INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NomArt VARCHAR(25) NOT NULL,
Categoria VARCHAR (50) NOT NULL,
Precio FLOAT NOT NULL CHECK (Precio > 0.00),
Stock INT NOT NULL CHECK (Stock >= 0)
);

CREATE TABLE PEDIDO	
(
  CodPe INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FecPed DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CodCli INT NOT NULL,
  FOREIGN KEY (CodCli) REFERENCES CLIENTE(CodCli)
);

CREATE TABLE FACTURA
(
  CodFac INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NumFac CHAR(7) UNIQUE NOT NULL CHECK (NumFac REGEXP '^(\d{4})([0-9]{3})$
'),
  CodPed INT NOT NULL,
  FOREIGN KEY (CodPed) REFERENCES PEDIDO(CodPe)
);

CREATE TABLE ART_PED
(
  CodPe INT NOT NULL,
  CodArt INT NOT NULL,
  CantArt INT NOT NULL,
  PRIMARY KEY (CodPe, CodArt),
  FOREIGN KEY (CodPe) REFERENCES PEDIDO(CodPe),
  FOREIGN KEY (CodArt) REFERENCES ARTICULO(CodArt)
);
